image: 'callym/rust-make-docker-compose:latest'

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - test
  - doc
  - build

test:cargo:
  stage: test
  script: 'cargo make ci-flow'

cache:
  paths:
    - cargo/
    - target/
