[package]
name = "diesel_pg_trgm"
version = "0.0.1"
authors = ["Callym <hi@callym.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.3", features = ["postgres"] }

[dev-dependencies]
lazy_static = "1.2"
